---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

inputs:
- name: bucket-waterbottle
outputs:
- name: output-waterbottle

run:
  path: ash
  args:
  - "-c"
  - |
    cp bucket-waterbottle/output.log output-waterbottle/processed.txt
    echo "finished" >> output-waterbottle/processed.txt
    ls -al
