---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

inputs:
- name: bucket-waterbottle
outputs:
- name: bucket-waterbottle

run:
  path: bash
  args:
  - "-c"
  - |
  cp bucket-waterbottle/output.log bucket-waterbottle/processed.txt
