---
resource_types:
- name: azure-blob
  type: docker-image
  source:
    repository: cfcloudops/azure-blobstore-concourse-resource

resources:
- name: azure-blobstore
  type: azure-blob
  source:
    storage_account_name: ((azure-storage-account-name))
    storage_access_key: ((azure-storage-access-key))
    container: ((azure-storage-container))
    regexp: blobfile-*
    environment: AzureCloud

jobs:
- name: 1-build-and-save-release-to-blobstore
  plan:
  - task: create-artifact
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      outputs:
      - name: build
      run:
        path: sh
        args:
        - -exc
        - |
          # Do your build steps here. Creating temporary file below as a sample:
          export CURRENT_TIMESTAMP=$(date +"%Y%m%d%H%S")
          echo "Sample build output file, timestamp: $CURRENT_TIMESTAMP" > ./build/myappfile.txt
          # Creating sample package file with a file name containing the new version number
          tar -cvzf ./blobfile-$CURRENT_TIMESTAMP.tar.gz  --directory=./build .
          mv ./blobfile-*.tar.gz ./build
          find .
  - put: azure-blobstore
    params: { file: ./build/blobfile-*.tar.gz }

- name: 2-trigger-when-new-file-is-added-to-azure-blobstore
  plan:
  - get: azure-blobstore
    trigger: true
    passed:
      - 1-build-and-save-release-to-blobstore
  - task: use-new-file
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      inputs:
      - name: azure-blobstore
      run:
        path: sh
        args:
        - -exc
        - |
          cd ./azure-blobstore
          ls -la
          echo "Version of release file retrieved: $(cat ./version). Extracting release file..."
          tar -xvf ./blobfile-*.tar.gz
          ls -la
          cat ./myappfile.txt
