groups: []
resources:
- name: repo-test-pipelines
  type: git
  source:
    branch: master
    uri: https://github.com/scottbri/test-pipelines
- name: my-timer
  type: time
  source:
    interval: 20m
resource_types: []
jobs:
- name: create-files
  public: true
  plan:
  - get: repo-test-pipelines
  - get: my-timer
    trigger: true
  - task: create-files
    file: repo-test-pipelines/tasks/create-files.yml

- name: process-files
  public: false
  plan:
  - get: repo-test-pipelines
  - passed: [create-files]
    trigger: true
  - task: process-files
    file: repo-test-pipelines/tasks/process-files.yml

- name: output-files
  public: false
  plan:
  - get: repo-test-pipelines
  - passed: [process-files]
    trigger: true
  - task: output-files
    file: repo-test-pipelines/tasks/output-files.yml
