groups: []
resources:
- name: repo-test-pipelines
  type: git
  source:
    branch: master
    uri: https://github.com/scottbri/test-pipelines
- name: my-timer
  type: time
  source:
    interval: 2m
resource_types: []
jobs:
- name: print_hello_world
  public: true
  plan:
  - get: repo-test-pipelines
  - task: print_hello_world
    file: repo-test-pipelines/tasks/print_hello_world/print_hello_world.yml
