resources:
- name: test-pipelines
  type: git
  source:
    uri: https://github.com/scottbri/test-pipelines
    branch: main

- name: hello-world-docker-image
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-hub-username))/hello-world

jobs:
- name: publish
  public: true
  plan:
  - get: test-pipelines
  - put: hello-world-docker-image
    params:
      build: tasks/docker
  - task: run
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ((docker-hub-username))/hello-world
      run:
        path: /bin/hello-world
        args: []
      params:
        NAME: ((docker-hub-username))/hello-world
