---
resources:
- name: trigger-every-4-minutes
  type: time
  source:
    interval: 4m
- name: trigger-every-10-minutes
  type: time
  source:
    interval: 10m
- name: manualtrigger
  type: time           # technique to trigger and propagate manual execution through pipeline
  source:
    interval: 10m

jobs:
- name: Manual-trigger
  plan:
  - get: manualtrigger
    trigger: false

- name: Run-Forrest-Run
  plan:
  - get: trigger-every-4-minutes
    trigger: true
  - get: trigger-every-10-minutes
    trigger: true
  - get: manualtrigger
    trigger: true
    passed:
      - Manual-trigger
  - task: do-your-task-here
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: sh
        args:
        - -exc
        - |
          echo "This job is automatically triggered every 3 minutes."
          sleep 10   # so you can see the running job effect in the UI

- name: Run-Bubba-Run
  plan:
  - get: trigger-every-4-minutes
    trigger: true
    passed:
      - Run-Forrest-Run
  - get: trigger-every-10-minutes
    trigger: true
    passed:
      - Run-Forrest-Run
  - get: manualtrigger
    trigger: true
    passed:
      - Run-Forrest-Run
  - task: do-another-task-here
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: sh
        args:
        - -exc
        - |
          echo "Output of second job's task."
          sleep 10   # so you can see the running job effect in the UI
