---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

outputs:
- name: bucket-waterbottle

run:
  path: ash
  args:
  - "-c"
  - |
    ls -al > bucket-waterbottle/output.log
    ls -al
